Use modern api. Fix chat formatter <message> placeholder duplicate. Add permissions per tag resolver.
EternalCodeTeam/ChatFormatter pull request #51
Opened 2022-12-22 03:43 UTC by Rollczi

2022-12-22 13:44 UTC, vLuckyyy approved these changes

2022-12-22 21:55 UTC, vLuckyyy requested changes

2022-12-22 21:55 UTC, vLuckyyy commented on chat-formatter/src/com/eternalcode/formatter/ChatController.java
> +        .put("chat.newline", StandardTags.newline())
chat -> chatformatter

2022-12-23 14:07 UTC, vLuckyyy approved these changes

2022-12-23 15:34 UTC, Jakubk15 approved these changes
Mam nadzieję, że faktycznie działa 😝

2022-12-23 15:35 UTC, merged